football/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name="football/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="football/logout.html"), name='logout'),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.TeamMatchesView.as_view(), name="team_matches"),
    path("lap/<int:pk>/", views.LapView.as_view(), name="lap"),
    path("match/create/", views.MatchCreateView.as_view(), name="match_create"),
    path("match/<int:pk>/delete/", views.MatchDeleteView.as_view(), name="match_delete"),
    path("match/<int:pk>/update/", views.MatchUpdateView.as_view(), name="match_update"),
    path("match/<int:pk>/update/lineup/<str:team_type>/", views.LineupUpdateView.as_view(), name="lineup"),
    path("match/<int:pk>/create/lineup/<str:team_type>/", views.LineupCreateView.as_view(), name="lineup_create"),
    path("match/<int:pk>/update/event/", views.EventCreateView.as_view(), name="event"),
    path("match/<int:pk>/update/event/<int:event_pk>/", views.TeamCreateEventView.as_view(), name="players_to_event"),
    path("match/<int:pk>/details/", views.MatchDetailsView.as_view(), name="match_details"),
    # path("match/<int:pk>/update/event/substitution/int:event_pk>/")
    path("table/", views.TableView.as_view(), name="table"),
    path("laps/", views.LapsListView.as_view(), name="laps_list"),
    path("team/<int:pk>/", views.TeamInfoView.as_view(), name="team_info"),
]

sport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('football/', include("football.urls")),
    path('admin/', admin.site.urls),
]

football/models.py
from django.db import models
from django.core.exceptions import ValidationError

class Team(models.Model):
    name = models.CharField(max_length=64, null=False, blank=False)
    city = models.CharField(max_length=64, null=False, blank=False)
    founded = models.DateField()
    stadium = models.CharField(max_length=64, blank=True)

    def __str__(self) -> str:
        return self.name

class Match(models.Model):
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home_matches')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away_matches')
    date = models.DateField()
    home_score = models.IntegerField()
    away_score = models.IntegerField()
    lap = models.IntegerField()

    def __str__(self) -> str:
        return self.home_team.name + " vs " + self.away_team.name
    
    def clean(self):
        if self.home_score < 0:
            raise ValidationError({'home_score': 'Wynik nie może być ujemny.'})
        if self.away_score < 0:
            raise ValidationError({'away_score': 'Wynik nie może być ujemny.'})
        if self.lap <=0:
            raise ValidationError({'lap': 'kolejka nie moze być ujemna'})
        if self.home_team == self.away_team:
            raise ValidationError({'away_team': 'drużyna gości nie może być taka sama jak drućyna gospodarzy'})


class Player(models.Model):
    POSITION=(
        ('gk', 'bramkarz'),
        ('df', 'obrońca'),
        ('mf', 'pomocnik'),
        ('st', 'napastnik')
    )
    team = models.ForeignKey(Team, models.SET_NULL,blank=True,null=True,)
    name = models.CharField(max_length=50)
    birth_day = models.DateField()
    position = models.CharField(max_length=2, choices=POSITION)
    nationality = models.CharField(max_length=40)

    def __str__(self):
        team_name = self.team.name if self.team else "Brak drużyny"
        return f"{self.name} ({team_name}) - {self.get_position_display()} - {self.nationality} - {self.birth_day}"
    
class Lineup(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name="lineups")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="lineups")
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="lineups")
    is_starting = models.BooleanField(default=True)  # Czy gracz zaczyna w pierwszym składzie
    on_bench = models.BooleanField(default=False) # Po zejściu z boiska

    def __str__(self):
        status = "Starting" if self.is_starting else "Substitute"
        return f"{self.player.name} ({status}) - {self.team.name} in {self.match}"

class Event(models.Model):
    EVENT_TYPES = [
        ("goal", "Bramka"),
        ("own_goal", "Bramka samobójcza"),
        ("yellow_card", "Żółta kartka"),
        ("red_card", "Czerwona kartka"),
        ("substitution", "Zmiana"),
    ]

    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name="events")
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True, related_name="events")
    player = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True, blank=True, related_name="events")
    event_type = models.CharField(max_length=20, choices=EVENT_TYPES)
    minute = models.PositiveIntegerField()
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.get_event_type_display()} - {self.match} ({self.minute} min)"

class Substitution(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, related_name="substitution", help_text="Wydarzenie związane z tą zmianą")
    player_in = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="substitutions_in",help_text="Zawodnik wchodzący na boisko")

    def __str__(self):
        return f"{self.player_in.name} za {self.event.player.name} z {self.event.team} {self.event.minute} mecz: {self.event.match}"

football/views.py
from typing import Any
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from django.db.models import Q, F, Count, Sum, Subquery, OuterRef
from django.http import HttpResponseRedirect
from django.contrib.auth import login
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from .models import Match, Team, Player, Lineup, Event, Substitution
from .forms import MatchForm, LineupForm, EventForm, TeamCreateEventForm
from .forms import RegisterForm


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'football/register.html'
    
    def form_valid(self, form):
        user = form.save()
        default_group, created = Group.objects.get_or_create(name='Uzytkownicy')
        user.groups.add(default_group)
        if user:
            login(self.request, user)

        return redirect('index')

class IndexView(generic.ListView):
    model = Team
    template_name = "football/index.html"

    def get_queryset(self):
       return Team.objects.all()

class TeamMatchesView(LoginRequiredMixin, generic.DetailView):
    model = Team
    template_name = "football/team_matches.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.object
        matches = Match.objects.filter(Q(home_team=team) | Q(away_team=team)).order_by('lap')
        context['matches'] = matches
        return context
    
class LapView(LoginRequiredMixin,generic.ListView):
    model = Match
    template_name = "football/lap.html" 

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        lap = self.kwargs['pk']
        matches = Match.objects.filter(lap=lap)
        context['matches'] = matches
        context['lap'] = lap
        return context
    
class MatchCreateView(PermissionRequiredMixin, CreateView):
    model = Match
    fields = ['lap', 'date','home_team', 'away_team', 'home_score', 'away_score']
    template_name = 'football/match_create.html'
    success_url = reverse_lazy('index')
    permission_required = ['football.add_match', 'football.view_match']

    def form_valid(self, form):
        match = form.save()  # Mecz zostaje zapisany i otrzymuje pk
        # Przekieruj do widoku szczegółowego lub update view, gdzie opcjonalnie można ustawić skład
        return redirect(reverse('match_details', kwargs={'pk': match.pk}))

class MatchDeleteView(PermissionRequiredMixin, DeleteView):
    model = Match
    template_name = 'football/match_delete.html'
    success_url = reverse_lazy('index')
    permission_required = ['football.delete_match', 'football.view_match']

class MatchUpdateView(PermissionRequiredMixin, UpdateView):
    model = Match
    form_class = MatchForm
    template_name = 'football/match_update.html'
    success_url = reverse_lazy('index')
    permission_required = ['football.change_match', 'football.view_match']

class TableView(LoginRequiredMixin,generic.ListView):
    model = Team
    template_name = 'football/table.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        teams_stat = Team.objects.annotate(
            home_wins=Count('home_matches', distinct=True, filter=Q(home_matches__home_score__gt=F('home_matches__away_score'))),
            away_wins=Count('away_matches', distinct=True, filter=Q(away_matches__away_score__gt=F('away_matches__home_score'))),
            home_draws=Count('home_matches', distinct=True, filter=Q(home_matches__home_score=F('home_matches__away_score'))),
            away_draws=Count('away_matches', distinct=True, filter=Q(away_matches__away_score=F('away_matches__home_score'))),
            home_loses=Count('home_matches', distinct=True, filter=Q(home_matches__home_score__lt=F('home_matches__away_score'))),
            away_loses=Count('away_matches', distinct=True, filter=Q(away_matches__away_score__lt=F('away_matches__home_score'))),
        ).annotate(
            wins=F('home_wins') + F('away_wins'),
            draws=F('home_draws') + F('away_draws'),
            loses=F('home_loses') + F('away_loses'),
            points=(F('wins') * 3) + (F('draws') * 1),
            home_goals_scored=Subquery(
                Match.objects.filter(home_team=OuterRef('pk'))
                .values('home_team')
                .annotate(total_goals=Sum('home_score'))
                .values('total_goals')
            ),
            away_goals_scored=Subquery(
                Match.objects.filter(away_team=OuterRef('pk'))
                .values('away_team')
                .annotate(total_goals=Sum('away_score'))
                .values('total_goals')
            ),
            home_goals_conceded=Subquery(
                Match.objects.filter(home_team=OuterRef('pk'))
                .values('home_team')
                .annotate(total_conceded=Sum('away_score'))
                .values('total_conceded')
            ),
            away_goals_conceded=Subquery(
                Match.objects.filter(away_team=OuterRef('pk'))
                .values('away_team')
                .annotate(total_conceded=Sum('home_score'))
                .values('total_conceded')
            ),

            # home_goals_scored=Sum('home_matches__home_score'),
            # away_goals_scored=Sum('away_matches__away_score'),
            goals_scored=F('home_goals_scored') + F('away_goals_scored'),
            # home_goals_conceded=Sum('home_matches__away_score'),
            # away_goals_conceded=Sum('away_matches__home_score'),
            goals_conceded=F('home_goals_conceded') + F('away_goals_conceded'),
            goals_difference=F('goals_scored') - F('goals_conceded'),
            matches=F('wins') + F('draws') + F('loses')

        ).order_by('-points', '-goals_difference', '-goals_scored')
        context['teams_stat'] = teams_stat

        return context
    
class LapsListView(LoginRequiredMixin,generic.ListView):
    model = Match
    template_name = 'football/laps_list.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        laps_list = Match.objects.values('lap').distinct()
        context['laps_list'] = laps_list
        return context

class TeamInfoView(LoginRequiredMixin,generic.DetailView):
    model = Team
    template_name = "football/team_info.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.object
    #    players = Player.objects.filter(team=team)
        context['goalkeepers'] = Player.objects.filter(team=team, position='gk')
        context['defenders'] = Player.objects.filter(team=team, position='df')
        context['midfielders'] = Player.objects.filter(team=team, position='mf')
        context['strikers'] = Player.objects.filter(team=team, position='st')
        return context

class LineupCreateView(PermissionRequiredMixin, CreateView):
    model = Lineup
    form_class = LineupForm
    template_name = "football/lineup_form.html"
    permission_required = ['football.add_lineup', 'football.view_lineup', 'football.view_player', 'football.view_team', 'football.view_match']

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        match = Match.objects.get(pk=self.kwargs['pk'])
        team_type = self.kwargs['team_type']
        team = match.home_team if team_type == 'home' else match.away_team
        kwargs['team'] = team
        return kwargs

    def form_valid(self, form):
        # Pobierz mecz na podstawie parametru z URL-a
        match = Match.objects.get(pk=self.kwargs['pk'])
        
        # Pobierz wybranych zawodników
        players = form.cleaned_data['players']
        
        # Pobierz drużynę (np. na podstawie team_type)
        team_type = self.kwargs.get('team_type')
        team = match.home_team if team_type == 'home' else match.away_team
        
        # Tworzenie rekordów w Lineup
        for player in players:
            Lineup.objects.create(
                match=match,
                player=player,
                team=team,
            )
        
        # Przekierowanie na sukces, bez wywoływania super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['selected_players'] = (
        list(map(int, self.request.POST.getlist('players'))) if self.request.method == 'POST' else []
        )

        match = Match.objects.get(pk=self.kwargs['pk'])
        team_type = self.kwargs['team_type']
        team = match.home_team if team_type == 'home' else match.away_team
        
        # Pobieranie zawodników według pozycji
        goalkeepers = Player.objects.filter(team=team, position='gk').order_by('name')
        defenders = Player.objects.filter(team=team, position='df').order_by('name')
        midfielders = Player.objects.filter(team=team, position='mf').order_by('name')
        strikers = Player.objects.filter(team=team, position='st').order_by('name')
        
        # Dodanie zawodników do kontekstu
        context['goalkeepers'] = goalkeepers
        context['defenders'] = defenders
        context['midfielders'] = midfielders
        context['strikers'] = strikers

        return context
    
    def get_success_url(self):
        return reverse('match_update', kwargs={'pk': self.kwargs['pk']})

class LineupUpdateView(PermissionRequiredMixin, UpdateView):
    model = Lineup
    form_class = LineupForm
    template_name = "football/lineup_form.html"
    permission_required = ['football.add_lineup', 'football.view_lineup', 'football.view_player', 'football.view_team', 'football.view_match']

football/templates/football/base.html
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>

<body>
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Drużyny</a></li>
                    {% if "Moderatorzy" in request.user.groups.all|join:", " %}
                    <li><a href="{% url 'match_create' %}" class="nav-link px-2 text-white">Wpisz wynik meczu</a></li>
                    {% endif %}
                    <li><a href="{% url 'table' %}" class="nav-link px-2 text-white">Tabele</a></li>
                    <li><a href="{% url 'laps_list' %}" class="nav-link px-2 text-white">Kolejki</a></li>
                </ul>
                <div class="text-end">

                    {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light me-2">Wyloguj</button>
                    </form>
                    Witaj, {{ user.username }}!
                    {% else %}
                    <form action="{% url 'login' %}?next={{ request.path }}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light me-2">Zaloguj</button>
                    </form>
                    <form action="{% url 'register' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning">Zarejestruj</button>
                    </form>{% endif %}
                </div>
            </div>

        </div>
    </header>

</body>
<style>
    .bg-yellow {
        background-color: #fff279;
        /* Jasny żółty */
    }

    .bg-green {
        background-color: #39723b;
        /* Jasny zielony */
    }
</style>
<main>

    <body class="bg-green text-light">
        <div class="row justify-content-center">
            <div class="col-md-7">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</main>

football/templates/football/event_form.html
{% extends "football/base.html" %}
{% block content %}

<div class="card">
  <div class="card-header">
    Dodaj wydarzenie do meczu: {{ match }}
  </div>
  <div class="card-body">
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Zapisz</button>
      </form>
  </div>
</div>

{% endblock %}

football/templates/football/index.html
{% extends "football/base.html" %}
{% block content %}




<div class="bd-example m-6 border-0">
    <table class="table">
        <thead>
            <tr class="text-white">
                <th>
                    Drużyny
                </th>
            </tr>
        </thead>
        <tbody>
            {% for team in team_list %}
            <tr class="{% cycle 'bg-light' 'bg-white' %}">
                <td>
                    <a href="{% url 'team_info' team.id %}" class="d-block text-decoration-none link-dark">
                        {{team.name}} </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}

football/templates/football/lap.html
{% extends "football/base.html" %}
{% block content %}

Kolejka nr {{lap}}
<div class="bd-example m-6 border-0">
    <table class="table">
        <thead>
            <tr class="bg-white">
                <th>data</th>
                <th>drużyny</th>
                <th>wynik</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for match in matches %}
            <tr class="{% cycle 'bg-light' 'bg-white' %}">
                <td>{{ match.date|date:"Y.m.d" }}</td>

                <td> <a href="{% url 'team_info' match.home_team.id %}"
                        class="text-decoration-none link-dark">{{match.home_team}}</a> - <a
                        href="{% url 'team_info' match.away_team.id %}"
                        class="text-decoration-none link-dark">{{match.away_team}}</a>
                </td>
                <td> {{match.home_score}} : {{match.away_score}}</td>
                <td>
                    <a href="{% url 'match_details' match.pk %}"> <span class="badge bg-dark">[szczegóły]</span> </a>
                    {% if "Moderatorzy" in request.user.groups.all|join:", " %}
                    <a href="{% url 'match_delete' match.pk %}"><span class="badge bg-danger">[usuń] </span> </a>
                    <a href="{% url 'match_update' match.pk %}"> <span class="badge bg-secondary">[popraw]</span> </a>
                    {% endif %}
                </td>
                {% endfor %}
                </ul>
                {% endblock %}
            </tr>
        </tbody>
    </table>
</div>

football/templates/football/laps_list.html
{% extends "football/base.html" %}
{% block content %}

<div class="bd-example m-6 border-0">
    <table class="table">
        <thead>
            <tr class="text-white">
                <th>
                    Kolejki
                </th>
            </tr>
        </thead>
        <tbody>

            {% for lap in laps_list %}
            <tr class="{% cycle 'bg-light' 'bg-white' %}">
                <td>
                    <a href="{% url 'lap' lap.lap %}" class="d-block text-decoration-none link-dark">
                        Kolejka nr {{lap.lap}} </a>
                </td>
                {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}

football/templates/football/login.html
{% extends "football/base.html" %}
{% block content %}
<div class="d-flex justify-content-center align-items-start" style="min-height: 100vh; padding-top: 10vh;">
    <div class="card text-dark bg-yellow" style="width: 18rem; min-height: 30vh;">
        <div class="card-header text-center">
            Logowanie
        </div>
        <div class="card-body d-flex flex-column justify-content-center">
            <form method="post">
                {% csrf_token %}
                <div>Login: {{ form.username }}</div>
                <br>
                <div>Haslo: {{ form.password }}</div>
                <br>
                <div class="d-flex justify-content-center">
                    <button type="submit">Zaloguj</button>
                </div>
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </div>
        <div class="card-footer text-center">
            Jeśli nie masz jeszcze konta <a href="{% url 'register' %}">zarejestruj się</a>
        </div>
    </div>
</div>
{% endblock %}

football/templates/football/logout.html
{% extends "football/base.html" %}
{% block content %}
<div>
    <h2>Wylogowano pomyślnie</h2>
    <p>Przejdź na <a href="{% url 'login' %}">stronę logowania</a></p>
</div>
{% endblock %}

football/templates/football/match_create.html
{% extends "football/base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    <div class="row">
        <div class="mb-3 col-lg-2 col-md-6 col-6">
            <label for="{{ form.lap.id_for_label }}" class="form-label">Kolejka</label>
            {{ form.lap }}
        </div>
        <div class="col-lg-8 col-md-2 col-12"></div>
        <div class="mb-3 col-lg-2 col-md-4 col-6">
            <label for="{{ form.date.id_for_label }}" class="form-label">Data</label>
            {{ form.date }}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col-lg-4 col-md-6 col-12">
            <label for="{{ form.home_team.id_for_label }}" class="form-label">Gospodarze</label>
            <br>
            {{ form.home_team }}
        </div>
        <div class="mb-3 col-lg-2 col-md-4 col-6">
            <label for="{{ form.home_score.id_for_label }}" class="form-label">Bramki</label>
            {{ form.home_score }}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col-lg-4 col-md-6 col-12">
            <label for="{{ form.away_team.id_for_label }}" class="form-label">Goście</label>
            <br>
            {{ form.away_team }}
        </div>
        <div class="mb-3 col-lg-2 col-md-4 col-6">
            <label for="{{ form.away_score.id_for_label }}" class="form-label">Bramki</label>
            {{ form.away_score }}
        </div>
    </div>

    <input type="submit" value="Zapisz">
</form>

<br>

{% endblock %}

football/templates/football/match_delete.html
{% extends "football/base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Jesteś pewny/pewna, że chcesz usunąć ten mecz?</p>
    <p>{{ object.home_team }} - {{ object.away_team }} {{ object.home_score }} : {{ object.away_score }} </p>
    <p>lap: {{ object.lap }}</p>
    <p>{{ object.date }}?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form> 

{% endblock %}

football/templates/football/match_details.html
{% extends "football/base.html" %}
{% block content %}
<div class="row">
    <div class="md-3 col-4 text-end">
        {{current_match.home_team}}
    </div>
    <div class="md-3 col-2 text-end">
        {{current_match.home_score}}
    </div>
    <div class="md-3 col-2">
        {{current_match.away_score}}
    </div>
    <div class="md-3 col-4">
        {{current_match.away_team}}
    </div>
</div>

<div class="row">
    <div class="col-6 ">
        {% for player in home%}
        <div class="row">
            <div class="col-8 {% cycle 'bg-light text-dark' 'bg-white text-dark' %} p-2">
                {{ player.0 }}
            </div>
            <div class="col-4 {% cycle 'bg-light text-dark' 'bg-white text-dark' %} p-2">
                {% for event in player.1 %}
                {{event.minute}} 
                {% if event.event_type == "yellow_card" %}
                <i class=" text-warning bi bi-square-fill"></i>
                {% elif event.event_type == "red_card" %}
                <i class=" text-danger bi bi-square-fill"></i>
                {% elif event.event_type == "goal" %}
                <i class="fa-solid fa-futbol"></i>                
                {% elif event.event_type == "own_goal" %}
                <i class=" text-danger fa-solid fa-futbol"></i>                
                {% elif event.event_type == "substitution" %}
                <i class=" text-danger bi bi-arrow-down"></i>             

                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-6">
        {% for player in away_team %}
        <div class="row">
            <div class="col-10 {% cycle 'bg-light text-dark' 'bg-white text-dark' %} p-2">
                {{ player.player.name }}
            </div>
            <div class="col-2 {% cycle 'bg-light text-dark' 'bg-white text-dark' %} p-2">
                {{ away_events.player }}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% if "Moderatorzy" in request.user.groups.all|join:", " %}
<div  class="d-grid gap-2 col-6 mx-auto">
    <a href="{% url 'match_update' match.pk %}" button class="btn btn-dark" type="button"> popraw </a></div>
{% endif %}

{% endblock %}

football/templates/football/players_to_event.html
{% extends "football/base.html" %}
{% block content %}

<h1>{{event.event_type}} w meczu: {{ match }} z {{ event.minute }} minuty. Drużyna {{ team }} </h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Zapisz</button>
</form>

{% endblock %}

football/templates/football/register.html
{% extends "football/base.html" %}
{% block content %}
<div class="d-flex justify-content-center align-items-start" style="min-height: 100vh; padding-top: 10vh;">
	<div class="card text-dark bg-yellow" style="width: 21rem; min-height: 48vh;">
		<div class="card-header text-center">
			Rejestracja
		</div>
		<div class="card-body d-flex flex-column justify-content-center">
			<form method="post">
				{% csrf_token %}
				<div class="row">
					<div class="col-4">Login:</div>
					<div class="col-8"> {{ form.username }}</div>
				</div>
				<br>
				<div class="row">
					<div class="col-4">e-mail:</div>
					<div class="col-8">{{ form.email }}</div>
				</div>
				<br>
				<div class="row">
					<div class="col-4">Hasło:</div>
					<div class="col-8"> {{ form.password1 }}</div>
				</div>
				<br>
				<div class="row">
					<div class="col-4">Potwierdź hasło:</div>
					<div class="col-8">{{ form.password2 }}</div>
				</div>
				<div class="d-flex justify-content-center">
					<button type="submit">Zarejestruj</button>
				</div>
				<input type="hidden" name="next" value="{{ next }}">

			</form>
		</div>
		<div class="card-footer text-center">
			Jeśli masz konto, <a href="{% url 'login' %}">zaloguj się</a>
		</div>
	</div>
</div>

{% endblock %}